### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by mosemister** [SoftwareEngTeam10/Main#1]
These are the things that need to be added

- [x] Add skills (backend)
- [x] Add View Skills (frontend)
- [x] Add create Skills (frontend)
- [x] add new group button in groups screen (front end)
- [x] add ability to move students to another group without swapping (front end)
- [x] ability to modify student details from admin (front end)
- [ ] change the role name without changing id (front end)
- [ ] attempt to even out groups (backend)
- [ ] add max teams count (frontend)
